class PartnersData:
    def __init__(self) -> None:
        self.data = [{
            'Facebook': {
                "utc_date": "2022-12-05",
                "athena_imp": 233,
                "previous_day_athena_imp": 389,
                "athena_DoD_drop": 34,
                "snowflake_imp": 3698740759,
                "snowflake_DoD_drop": -1.21,
                "snowflake_YoY_drop": 18.29,
                "previous_day_snowflake_imp": 89,
                "previous_yr_snowflake_imp": 30,
                "diff_athena_snowflake": -100.0,
            }
        },{
            'Snapchat': {
                "utc_date": "2022-12-06",
                "athena_imp": 233,
                "previous_day_athena_imp": 389,
                "athena_DoD_drop": 34,
                "snowflake_imp": 3698740759,
                "snowflake_DoD_drop": -1.21,
                "snowflake_YoY_drop": 18.29,
                "previous_day_snowflake_imp": 89,
                "previous_yr_snowflake_imp": 30,
                "diff_athena_snowflake": -100.0,
            }
        },
        {
            'Yahoo': {
                "utc_date": "2022-12-06",
                "athena_imp": 233,
                "previous_day_athena_imp": 389,
                "athena_DoD_drop": 34,
                "snowflake_imp": 3698740759,
                "snowflake_DoD_drop": -1.21,
                "snowflake_YoY_drop": 18.29,
                "previous_day_snowflake_imp": 89,
                "previous_yr_snowflake_imp": 30,
                "diff_athena_snowflake": -100.0,
            }
        },
        {
            'Pinterest': {
                "utc_date": "2022-12-06",
                "athena_imp": 233,
                "previous_day_athena_imp": 389,
                "athena_DoD_drop": 34,
                "snowflake_imp": 3698740759,
                "snowflake_DoD_drop": -1.21,
                "snowflake_YoY_drop": 18.29,
                "previous_day_snowflake_imp": 89,
                "previous_yr_snowflake_imp": 30,
                "diff_athena_snowflake": -100.0,
            }
        },
        {
            'Linkedin': {
                "utc_date": "2022-12-06",
                "athena_imp": 233,
                "previous_day_athena_imp": 389,
                "athena_DoD_drop": 34,
                "snowflake_imp": 3698740759,
                "snowflake_DoD_drop": -1.21,
                "snowflake_YoY_drop": 18.29,
                "previous_day_snowflake_imp": 89,
                "previous_yr_snowflake_imp": 30,
                "diff_athena_snowflake": -100.0,
            }
        },
        {
            'Spotify': {
                "utc_date": "2022-12-06",
                "athena_imp": 233,
                "previous_day_athena_imp": 389,
                "athena_DoD_drop": 34,
                "snowflake_imp": 3698740759,
                "snowflake_DoD_drop": -1.21,
                "snowflake_YoY_drop": 18.29,
                "previous_day_snowflake_imp": 89,
                "previous_yr_snowflake_imp": 30,
                "diff_athena_snowflake": -100.0,
            }
        },
        {
            'Twitter': {
                "utc_date": "2022-12-06",
                "athena_imp": 233,
                "previous_day_athena_imp": 389,
                "athena_DoD_drop": 34,
                "snowflake_imp": 3698740759,
                "snowflake_DoD_drop": -1.21,
                "snowflake_YoY_drop": 18.29,
                "previous_day_snowflake_imp": 89,
                "previous_yr_snowflake_imp": 30,
                "diff_athena_snowflake": -100.0,
            }
        },
        {
            'Youtube - Google Ads': {
                "utc_date": "2022-12-06",
                "athena_imp": 233,
                "previous_day_athena_imp": 389,
                "athena_DoD_drop": 34,
                "snowflake_imp": 3698740759,
                "snowflake_DoD_drop": -1.21,
                "snowflake_YoY_drop": 18.29,
                "previous_day_snowflake_imp": 89,
                "previous_yr_snowflake_imp": 30,
                "diff_athena_snowflake": -100.0,
            }
        },
        {
            'Youtube - DV 360': {
                "utc_date": "2022-12-06",
                "athena_imp": 233,
                "previous_day_athena_imp": 389,
                "athena_DoD_drop": 34,
                "snowflake_imp": 3698740759,
                "snowflake_DoD_drop": -1.21,
                "snowflake_YoY_drop": 18.29,
                "previous_day_snowflake_imp": 89,
                "previous_yr_snowflake_imp": 30,
                "diff_athena_snowflake": -100.0,
            }
        },
        {
            'Youtube - Partner Sold': {
                "utc_date": "2022-12-06",
                "athena_imp": 233,
                "previous_day_athena_imp": 389,
                "athena_DoD_drop": 34,
                "snowflake_imp": 3698740759,
                "snowflake_DoD_drop": -1.21,
                "snowflake_YoY_drop": 18.29,
                "previous_day_snowflake_imp": 89,
                "previous_yr_snowflake_imp": 30,
                "diff_athena_snowflake": -100.0,
            }
        },
        {
            'Youtube - Reserve': {
                "utc_date": "2022-12-06",
                "athena_imp": 233,
                "previous_day_athena_imp": 389,
                "athena_DoD_drop": 34,
                "snowflake_imp": 3698740759,
                "snowflake_DoD_drop": -1.21,
                "snowflake_YoY_drop": 18.29,
                "previous_day_snowflake_imp": 89,
                "previous_yr_snowflake_imp": 30,
                "diff_athena_snowflake": -100.0,
            }
        }]

        self.excel_data = {
            'Facebook': {
                    "utc_date": "2022-12-06",
                    "athena_imp": 233,
                    "previous_day_athena_imp": 389,
                    "athena_DoD_drop": 34,
                    "snowflake_imp": 3698740759,
                    "snowflake_DoD_drop": -1.21,
                    "snowflake_YoY_drop": 18.29,
                    "previous_day_snowflake_imp": 89,
                    "previous_yr_snowflake_imp": 30,
                    "diff_athena_snowflake": -100.0,
                },
            'Snapchat': {
                    "utc_date": "2022-12-06",
                    "athena_imp": 233,
                    "previous_day_athena_imp": 389,
                    "athena_DoD_drop": 34,
                    "snowflake_imp": 3698740759,
                    "snowflake_DoD_drop": -1.21,
                    "snowflake_YoY_drop": 18.29,
                    "previous_day_snowflake_imp": 89,
                    "previous_yr_snowflake_imp": 30,
                    "diff_athena_snowflake": -100.0,
                },
            'Yahoo': {
                "utc_date": "2022-12-06",
                "athena_imp": 233,
                "previous_day_athena_imp": 389,
                "athena_DoD_drop": 34,
                "snowflake_imp": 3698740759,
                "snowflake_DoD_drop": -1.21,
                "snowflake_YoY_drop": 18.29,
                "previous_day_snowflake_imp": 89,
                "previous_yr_snowflake_imp": 30,
                "diff_athena_snowflake": -100.0,
            },
            'Pinterest': {
                "utc_date": "2022-12-06",
                "athena_imp": 233,
                "previous_day_athena_imp": 389,
                "athena_DoD_drop": 34,
                "snowflake_imp": 3698740759,
                "snowflake_DoD_drop": -1.21,
                "snowflake_YoY_drop": 18.29,
                "previous_day_snowflake_imp": 89,
                "previous_yr_snowflake_imp": 30,
                "diff_athena_snowflake": -100.0,
            },
            'Linkedin': {
                "utc_date": "2022-12-06",
                "athena_imp": 233,
                "previous_day_athena_imp": 389,
                "athena_DoD_drop": 34,
                "snowflake_imp": 3698740759,
                "snowflake_DoD_drop": -1.21,
                "snowflake_YoY_drop": 18.29,
                "previous_day_snowflake_imp": 89,
                "previous_yr_snowflake_imp": 30,
                "diff_athena_snowflake": -100.0,
            },
            'Spotify': {
                "utc_date": "2022-12-06",
                "athena_imp": 233,
                "previous_day_athena_imp": 389,
                "athena_DoD_drop": 34,
                "snowflake_imp": 3698740759,
                "snowflake_DoD_drop": -1.21,
                "snowflake_YoY_drop": 18.29,
                "previous_day_snowflake_imp": 89,
                "previous_yr_snowflake_imp": 30,
                "diff_athena_snowflake": -100.0,
            },
            'Twitter': {
                "utc_date": "2022-12-06",
                "athena_imp": 233,
                "previous_day_athena_imp": 389,
                "athena_DoD_drop": 34,
                "snowflake_imp": 3698740759,
                "snowflake_DoD_drop": -1.21,
                "snowflake_YoY_drop": 18.29,
                "previous_day_snowflake_imp": 89,
                "previous_yr_snowflake_imp": 30,
                "diff_athena_snowflake": -100.0,
            },
            'Youtube - Google Ads': {
                "utc_date": "2022-12-06",
                "athena_imp": 233,
                "previous_day_athena_imp": 389,
                "athena_DoD_drop": 34,
                "snowflake_imp": 3698740759,
                "snowflake_DoD_drop": -1.21,
                "snowflake_YoY_drop": 18.29,
                "previous_day_snowflake_imp": 89,
                "previous_yr_snowflake_imp": 30,
                "diff_athena_snowflake": -100.0,
            },
            'Youtube - DV 360': {
                "utc_date": "2022-12-06",
                "athena_imp": 233,
                "previous_day_athena_imp": 389,
                "athena_DoD_drop": 34,
                "snowflake_imp": 3698740759,
                "snowflake_DoD_drop": -1.21,
                "snowflake_YoY_drop": 18.29,
                "previous_day_snowflake_imp": 89,
                "previous_yr_snowflake_imp": 30,
                "diff_athena_snowflake": -100.0,
            },
            'Youtube - Partner Sold': {
                "utc_date": "2022-12-06",
                "athena_imp": 233,
                "previous_day_athena_imp": 389,
                "athena_DoD_drop": 34,
                "snowflake_imp": 3698740759,
                "snowflake_DoD_drop": -1.21,
                "snowflake_YoY_drop": 18.29,
                "previous_day_snowflake_imp": 89,
                "previous_yr_snowflake_imp": 30,
                "diff_athena_snowflake": -100.0,
            },
            'Youtube - Reserve': {
                "utc_date": "2022-12-06",
                "athena_imp": 233,
                "previous_day_athena_imp": 389,
                "athena_DoD_drop": 34,
                "snowflake_imp": 3698740759,
                "snowflake_DoD_drop": -1.21,
                "snowflake_YoY_drop": 18.29,
                "previous_day_snowflake_imp": 89,
                "previous_yr_snowflake_imp": 30,
                "diff_athena_snowflake": -100.0,
            }
        }

    def get_partners_data(self):
        return self.data, self.excel_data